lib/turret_web/router.ex
defmodule TurretWeb.Router do
  use TurretWeb, :router

  import TurretWeb.UserAuth

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_user
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", TurretWeb do
    pipe_through :browser

    get "/", PageController, :index
  end

  # Enables LiveDashboard only for development
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: TurretWeb.Telemetry
    end
  end

  scope "/", TurretWeb do
    pipe_through [:browser, :redirect_if_user_is_authenticated]

    get "/users/register", UserRegistrationController, :new
    post "/users/register", UserRegistrationController, :create
    get "/users/log_in", UserSessionController, :new
    post "/users/log_in", UserSessionController, :create
    get "/users/reset_password", UserResetPasswordController, :new
    post "/users/reset_password", UserResetPasswordController, :create
    get "/users/reset_password/:token", UserResetPasswordController, :edit
    put "/users/reset_password/:token", UserResetPasswordController, :update
  end

  scope "/", TurretWeb do
    pipe_through [:browser, :require_authenticated_user]

    get "/users/settings", UserSettingsController, :index

    get "/users/settings/email", UserEmailSettingsController, :edit
    put "/users/settings/email", UserEmailSettingsController, :update
    get "/users/settings/email/:token", UserEmailSettingsController, :confirm_email

    get "/users/settings/password", UserPasswordSettingsController, :edit
    put "/users/settings/password", UserPasswordSettingsController, :update

    get "/users/settings/sessions", UserSessionSettingsController, :index
    delete "/users/settings/sessions/:session_id", UserSessionSettingsController, :delete
  end

  scope "/", TurretWeb do
    pipe_through [:browser]

    delete "/users/log_out", UserSessionController, :delete
    get "/users/confirm", UserConfirmationController, :new
    post "/users/confirm", UserConfirmationController, :create
    get "/users/confirm/:token", UserConfirmationController, :confirm
  end
end

lib/turret_web/controllers/user_password_settings_controller.ex
defmodule TurretWeb.UserPasswordSettingsController do
  use TurretWeb, :controller

  alias Turret.Accounts
  alias TurretWeb.UserAuth

  plug :assign_changeset

  def edit(conn, _params) do
    render(conn, "edit.html")
  end

  def update(conn, %{"current_password" => password, "user" => user_params}) do
    user = conn.assigns.current_user

    case Accounts.update_user_password(user, password, user_params) do
      {:ok, user} ->
        conn
        |> put_flash(:info, "Password updated successfully.")
        |> put_session(:user_return_to, Routes.user_settings_path(conn, :index))
        |> UserAuth.log_in_user(user)

      {:error, changeset} ->
        render(conn, "edit.html", changeset: changeset)
    end
  end

  defp assign_changeset(conn, _opts) do
    user = conn.assigns.current_user

    conn
    |> assign(:changeset, Accounts.change_user_password(user))
  end
end

lib/turret_web/views/user_password_settings_view.ex
defmodule TurretWeb.UserPasswordSettingsView do
  use TurretWeb, :view
end

lib/turret_web/templates/user_password_settings/edit.html.eex
<h1>Change password</h1>

<%= form_for @changeset, Routes.user_password_settings_path(@conn, :update), fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <%= label f, :password, "New password" %>
  <%= password_input f, :password, required: true %>
  <%= error_tag f, :password %>

  <%= label f, :password_confirmation, "Confirm new password" %>
  <%= password_input f, :password_confirmation, required: true %>
  <%= error_tag f, :password_confirmation %>

  <%= label f, :current_password, for: "current_password_for_password" %>
  <%= password_input f, :current_password, required: true, name: "current_password", id: "current_password_for_password" %>
  <%= error_tag f, :current_password %>

  <div>
    <%= submit "Change password" %>
  </div>
<% end %>